# Generated by Django 2.1.5 on 2019-06-15 11:40

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, validators=[users.validators.forbid_username]),
        ),
    ]
