# Generated by Django 2.1.5 on 2019-06-13 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0002_auto_20190612_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='winners',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
