# Generated by Django 2.1.5 on 2019-06-14 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='base_score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 16, 33, 23, 722398, tzinfo=utc)),
        ),
    ]
