# Generated by Django 2.1.5 on 2019-06-14 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20190614_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 16, 34, 39, 282341, tzinfo=utc)),
        ),
    ]
