# Generated by Django 2.1.5 on 2019-06-14 19:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20190614_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='winners',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='contest',
        ),
        migrations.AddField(
            model_name='problem',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 19, 8, 45, 561375, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='problem',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 19, 8, 45, 561351, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 19, 8, 45, 561771, tzinfo=utc)),
        ),
    ]
