# Generated by Django 2.1.5 on 2019-06-14 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20190614_1908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contest',
        ),
        migrations.AlterField(
            model_name='problem',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 19, 29, 25, 9766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 19, 29, 25, 9744, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 19, 29, 25, 10184, tzinfo=utc)),
        ),
    ]
