# Generated by Django 2.1.5 on 2019-06-15 11:40

import contests.helpers
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_auto_20190614_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 11, 40, 11, 256137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 11, 40, 11, 256107, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.FileField(upload_to=contests.helpers.gen_file_name),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 11, 40, 11, 256697, tzinfo=utc)),
        ),
    ]
