# Generated by Django 2.1.5 on 2019-06-15 13:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_auto_20190615_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 13, 20, 56, 4117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 13, 20, 56, 4086, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 13, 20, 56, 4711, tzinfo=utc)),
        ),
    ]
