# Generated by Django 2.2.2 on 2019-06-15 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_auto_20190615_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sub_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
